In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import least_squares

In [3]:
EARTH_RAD = 6378

def generate_sat(num_sat=4, altitude=20000):
    satellites = []
    for i in range(num_sat):
        angle = i * (2 * np.pi / num_sat) 
        x = (EARTH_RAD + altitude) * np.cos(angle)
        y = (EARTH_RAD + altitude) * np.sin(angle)
        z = 0

        satellites.append([x,y,z])
    
    return np.array(satellites)

sat_positions = generate_sat(6)
sat_positions

array([[ 2.63780000e+04,  0.00000000e+00,  0.00000000e+00],
       [ 1.31890000e+04,  2.28440181e+04,  0.00000000e+00],
       [-1.31890000e+04,  2.28440181e+04,  0.00000000e+00],
       [-2.63780000e+04,  3.23037333e-12,  0.00000000e+00],
       [-1.31890000e+04, -2.28440181e+04,  0.00000000e+00],
       [ 1.31890000e+04, -2.28440181e+04,  0.00000000e+00]])

In [5]:
# true receiver position
true_position = np.array([1000, 2000, 300])

print(f"Receiver Coordinates: {true_position}")

Receiver Coordinates: [1000 2000  300]


In [6]:
def compute_distances(receiver_pos, satellites):
    distances = []

    for sat in satellites:
        dist = np.linalg.norm(receiver_pos - sat)
        distances.append(dist)
    
    return np.array(distances)

true_distances = compute_distances(true_position, sat_positions)
true_distances

array([25458.45407718, 24148.18443685, 25216.87553199, 27452.59339297,
       28611.93730603, 27674.66271527])

In [8]:
def add_noise(distances, noise_level=0.01):
    noise = np.random.normal(0, noise_level, size=len(distances))
    return distances + noise

measured_distances = add_noise(true_distances)
measured_distances

array([25458.43628414, 24148.17413802, 25216.85784817, 27452.59849713,
       28611.94003226, 27674.67419474])