In [5]:
import warnings
import numpy as np

warnings.filterwarnings("ignore")

print(np.__version__)

2.2.6


In [2]:
# arrays

arr = np.array([1,2,3]) # rank = 1
print(type(arr))
print(arr.shape)
print(arr[0], arr[2])
arr[0] = np.zeros(1)
print(arr)

<class 'numpy.ndarray'>
(3,)
1 3
[0 2 3]


In [9]:
nums = np.array([[1,2,3],
                 [4,5,6]])

print(f"dimensions: {nums.ndim}")
print(f"size: {nums.size}")
print(f"dtype: {nums.dtype}")
print(f"itemsize: {nums.itemsize}")

dimensions: 2
size: 6
dtype: int64
itemsize: 8


In [11]:
print(np.array([1,2,3], dtype=float))
print(np.array([1,2,3], dtype=np.int32))
print(np.array([1,2,3], dtype=np.bool))

[1. 2. 3.]
[1 2 3]
[ True  True  True]


In [3]:
# rank 2 array

b = np.array([[1,2], [3,4]])
print(b)
print(b.shape)
print(type(b))

for rows in b:
    print(rows)

print(b[0, 1]) # value in the 0th row and 1st col

[[1 2]
 [3 4]]
(2, 2)
<class 'numpy.ndarray'>
[1 2]
[3 4]
2


In [4]:
# other methods of array creation

t1 = np.zeros((3,3))
print(t1, end="\n\n")

t2 = np.ones((2,2))
print(t2, end="\n\n")

t3 = np.full((4,4), 11)
print(t3, end="\n\n")

# identity matrix
t4 = np.eye(3) 
print(t4, end="\n\n")

t5 = np.random.random((2,2))
print(t5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]]

[[11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



[[0.13801841 0.71325368]
 [0.39469688 0.70966921]]
