In [9]:
import warnings
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

In [10]:
# arrays

arr = np.array([1,2,3]) # rank = 1
print(type(arr))
print(arr.shape)
print(arr[0], arr[2])
arr[0] = np.zeros(1)
print(arr)

<class 'numpy.ndarray'>
(3,)
1 3
[0 2 3]


In [16]:
# rank 2 array

b = np.array([[1,2], [3,4]])
print(b)
print(b.shape)
print(type(b))

for rows in b:
    print(rows)

print(b[0, 1]) # value in the 0th row and 1st col

[[1 2]
 [3 4]]
(2, 2)
<class 'numpy.ndarray'>
[1 2]
[3 4]
2


In [22]:
# other methods of array creation

t1 = np.zeros((3,3))
print(t1, end="\n\n")

t2 = np.ones((2,2))
print(t2, end="\n\n")

t3 = np.full((4,4), 11)
print(t3, end="\n\n")

# identity matrix
t4 = np.eye(3) 
print(t4, end="\n\n")

t5 = np.random.random((2,2))
print(t5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]]

[[11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0.3295806  0.6651552 ]
 [0.91330585 0.54883946]]
