In [3]:
# scalars are 0D tensors
# truly dense tensors   --> numpy.ndarray
# tensors with autodiff --> torch.tensor

import numpy as np

In [26]:
vector = np.array([1, 2, 3])

matrix = np.array([
    [1, 2],
    [2, 1]
])

tensor3D = np.array([
    [[1, 2, 3]],  # 1x3 matrix
    [[4, 5, 6]],  # 1x3 matrix
    [[7, 8, 9]]   # 1x3 matrix
])

print(vector, '\n')
print(matrix, '\n')
print(tensor3D)


[1 2 3] 

[[1 2]
 [2 1]] 

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [27]:
print(vector.shape, '\n')
print(matrix.shape, '\n')
print(tensor3D.shape, '\n') # (3,1,3) --> 3 ==> 1x3 matrices


(3,) 

(2, 2) 

(3, 1, 3) 



In [31]:
print(tensor3D[0, 0, 1])
print(tensor3D[2, 0, :]) # print all elements from the 0th entry -> print all vals in the first row

2
[7 8 9]


In [35]:
# tensor operations

a = np.array([[1, 2], [3, 4]])
b = np.array([[11, 12], [13, 14]])

print(a + b, '\n')
print(a - b, '\n')

[[12 14]
 [16 18]] 

[[-10 -10]
 [-10 -10]] 



In [36]:
# matrix mult
a @ b

array([[37, 40],
       [85, 92]])

In [41]:
# tensor reshaping

x = np.arange(10)
x_reshape = x.reshape(5,2)

print(x, '\n')
print(x_reshape, '\n')

[0 1 2 3 4 5 6 7 8 9] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 



In [2]:
import torch

torch.__version__

'2.7.1+cpu'

In [ ]:
# 0D scalar

tens = torch.tensor(100)
tens

tensor(100)

In [5]:
# 1D vector

vec = torch.tensor([1, 2, 3])
vec

tensor([1, 2, 3])

In [7]:
# 2D matrix

mat = torch.tensor([
    [1, 2],
    [3, 4]
])

mat

tensor([[1, 2],
        [3, 4]])

In [8]:
# special tensors

zeros = torch.zeros(4, 5)
ones = torch.ones(3, 3)
random_t = torch.rand(2, 6)

print(zeros)
print(ones)
print(random_t)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6696, 0.3501, 0.6299, 0.9721, 0.4666, 0.1090],
        [0.7662, 0.7409, 0.1892, 0.9083, 0.4849, 0.3036]])


In [9]:
tens_ = torch.tensor([
    [1.09, 2.04],
    [3.09, 4.04]
])

tens_

tensor([[1.0900, 2.0400],
        [3.0900, 4.0400]])

In [15]:
## tensor properties

test = torch.rand(3, 4)

print("shape: ",test.shape)
print("test: ",test.ndim)
print("dtype: ",test.dtype)
print("device: ",test.device)
print("size: ",test.size)

shape:  torch.Size([3, 4])
test:  2
dtype:  torch.float32
device:  cpu
size:  <built-in method size of Tensor object at 0x00000235312DC7D0>


In [19]:
# modifying data types of tensor members


reg_tens = torch.tensor([1 , 2, 3])
print(reg_tens.dtype)

tens_float = reg_tens.float()
print(tens_float.dtype)

torch.int64
torch.float32


In [20]:
# indexing and slicing of torch tensors

x = torch.tensor([
    [1, 2, 4],
    [5, 6, 7]
])

print(x[0])    # 1st row
print(x[:, 1]) # all row entries for the 2nd column
print(x[1, 2]) # 2nd row 3rd element

tensor([1, 2, 4])
tensor([2, 6])
tensor(7)


In [21]:
# indexing using bools

x[x > 3]

tensor([4, 5, 6, 7])

In [22]:
# tensor operations

A = torch.tensor([1., 2., 3.])
B = torch.tensor([4., 5., 6.])

A + B

tensor([5., 7., 9.])

In [23]:
A - B

tensor([-3., -3., -3.])

In [24]:
A**3

tensor([ 1.,  8., 27.])

In [25]:
A @ B

tensor(32.)

In [26]:
torch.matmul(A, B)

tensor(32.)

In [28]:
# reductions

red_t = torch.rand(3, 4)

print(red_t.sum())
print(red_t.mean(dim=0))
print(red_t.max(dim=1))

tensor(6.1519)
tensor([0.6508, 0.8299, 0.3868, 0.1832])
torch.return_types.max(
values=tensor([0.7693, 0.8670, 0.8533]),
indices=tensor([1, 1, 1]))
