In [3]:
# scalars are 0D tensors
# truly dense tensors   --> numpy.ndarray
# tensors with autodiff --> torch.tensor

import numpy as np

In [26]:
vector = np.array([1, 2, 3])

matrix = np.array([
    [1, 2],
    [2, 1]
])

tensor3D = np.array([
    [[1, 2, 3]],  # 1x3 matrix
    [[4, 5, 6]],  # 1x3 matrix
    [[7, 8, 9]]   # 1x3 matrix
])

print(vector, '\n')
print(matrix, '\n')
print(tensor3D)


[1 2 3] 

[[1 2]
 [2 1]] 

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [27]:
print(vector.shape, '\n')
print(matrix.shape, '\n')
print(tensor3D.shape, '\n') # (3,1,3) --> 3 ==> 1x3 matrices


(3,) 

(2, 2) 

(3, 1, 3) 



In [28]:
print(tensor3D[0, 0, 1])
print(tensor3D[2, 0, :]) # print all elements from the 0th entry -> print all vals in the first row

2
[7 8 9]
