In [3]:
# scalars are 0D tensors
# truly dense tensors   --> numpy.ndarray
# tensors with autodiff --> torch.tensor

import numpy as np

In [11]:
vector = np.array([1, 2, 3])

matrix = np.array([
    [1, 2],
    [2, 1]
])

tensor3D = np.array([
    [[1, 2, 3]],  # 1x3 matrix
    [[1, 2, 3]],  # 1x3 matrix
    [[1, 2, 3]]   # 1x3 matrix
])

print(vector, '\n')
print(matrix, '\n')
print(tensor3D)


[1 2 3] 

[[1 2]
 [2 1]] 

[[[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]]


In [12]:
print(vector.shape, '\n')
print(matrix.shape, '\n')
print(tensor3D.shape, '\n') # (3,1,3) --> 3 ==> 1x3 matrices


(3,) 

(2, 2) 

(3, 1, 3) 

