In [3]:
# scalars are 0D tensors
# truly dense tensors   --> numpy.ndarray
# tensors with autodiff --> torch.tensor

import numpy as np

In [26]:
vector = np.array([1, 2, 3])

matrix = np.array([
    [1, 2],
    [2, 1]
])

tensor3D = np.array([
    [[1, 2, 3]],  # 1x3 matrix
    [[4, 5, 6]],  # 1x3 matrix
    [[7, 8, 9]]   # 1x3 matrix
])

print(vector, '\n')
print(matrix, '\n')
print(tensor3D)


[1 2 3] 

[[1 2]
 [2 1]] 

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [27]:
print(vector.shape, '\n')
print(matrix.shape, '\n')
print(tensor3D.shape, '\n') # (3,1,3) --> 3 ==> 1x3 matrices


(3,) 

(2, 2) 

(3, 1, 3) 



In [31]:
print(tensor3D[0, 0, 1])
print(tensor3D[2, 0, :]) # print all elements from the 0th entry -> print all vals in the first row

2
[7 8 9]


In [35]:
# tensor operations

a = np.array([[1, 2], [3, 4]])
b = np.array([[11, 12], [13, 14]])

print(a + b, '\n')
print(a - b, '\n')

[[12 14]
 [16 18]] 

[[-10 -10]
 [-10 -10]] 



In [36]:
# matrix mult
a @ b

array([[37, 40],
       [85, 92]])

In [41]:
# tensor reshaping

x = np.arange(10)
x_reshape = x.reshape(5,2)

print(x, '\n')
print(x_reshape, '\n')

[0 1 2 3 4 5 6 7 8 9] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 



In [2]:
import torch

torch.__version__

'2.7.1+cpu'

In [ ]:
# 0D scalar

tens = torch.tensor(100)
tens

tensor(100)

In [5]:
# 1D vector

vec = torch.tensor([1, 2, 3])
vec

tensor([1, 2, 3])

In [7]:
# 2D matrix

mat = torch.tensor([
    [1, 2],
    [3, 4]
])

mat

tensor([[1, 2],
        [3, 4]])

In [8]:
# special tensors

zeros = torch.zeros(4, 5)
ones = torch.ones(3, 3)
random_t = torch.rand(2, 6)

print(zeros)
print(ones)
print(random_t)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6696, 0.3501, 0.6299, 0.9721, 0.4666, 0.1090],
        [0.7662, 0.7409, 0.1892, 0.9083, 0.4849, 0.3036]])


In [9]:
tens_ = torch.tensor([
    [1.09, 2.04],
    [3.09, 4.04]
])

tens_

tensor([[1.0900, 2.0400],
        [3.0900, 4.0400]])

In [15]:
## tensor properties

test = torch.rand(3, 4)

print("shape: ",test.shape)
print("test: ",test.ndim)
print("dtype: ",test.dtype)
print("device: ",test.device)
print("size: ",test.size)

shape:  torch.Size([3, 4])
test:  2
dtype:  torch.float32
device:  cpu
size:  <built-in method size of Tensor object at 0x00000235312DC7D0>
