In [1]:
import numpy as np

In [5]:
# standardization

x = np.array([
    [10 ,200],
    [60 ,180],
    [100 ,2000]
])

x_std = (x - x.mean(axis=0)) / x.std(axis=0)
print(x_std, end="\n\n")
print(x_std.mean(), end="\n\n") # almost 0 mean
print(x_std.std(), end="\n\n")  # std dev = 1

[[-1.26750044 -0.69535494]
 [ 0.09053575 -0.71879387]
 [ 1.1769647   1.41414882]]

7.401486830834377e-17

1.0



In [9]:
# train validation split - manual

np.random.seed(42)

a = np.random.rand(100, 5)
b = np.random.randint(0, 2, size=100)

indices = np.random.permutation(len(a))
train_size = int(0.7 * len(a))

train_idx, val_idx = indices[:train_size], indices[train_size:]

a_train, a_val = a[train_idx], a[val_idx]
b_train, b_val = b[train_idx], b[val_idx]

print(a_train, end="\n\n")
print(b_train, end="\n\n")

[[0.4937956  0.52273283 0.42754102 0.02541913 0.10789143]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]
 [0.93075733 0.85841275 0.42899403 0.75087107 0.75454287]
 [0.31897563 0.84487531 0.02327194 0.81446848 0.28185477]
 [0.87146059 0.80367208 0.18657006 0.892559   0.53934224]
 [0.64203165 0.08413996 0.16162871 0.89855419 0.60642906]
 [0.80936116 0.81011339 0.86707232 0.91324055 0.5113424 ]
 [0.00919705 0.10147154 0.66350177 0.00506158 0.16080805]
 [0.62939864 0.69574869 0.45454106 0.62755808 0.58431431]
 [0.94045858 0.95392858 0.91486439 0.3701587  0.01545662]
 [0.36778313 0.63230583 0.63352971 0.53577468 0.09028977]
 [0.24398964 0.97301055 0.39309772 0.89204656 0.63113863]
 [0.49161588 0.47347177 0.17320187 0.43385165 0.39850473]
 [0.38610264 0.96119056 0.90535064 0.19579113 0.0693613 ]
 [0.09310277 0.89721576 0.90041806 0.63310146 0.33902979]
 [0.67756436 0.01658783 0.51209306 0.22649578 0.64517279]
 [0.0407288  0.85546058 0.70365786 0.47417383 0.09783416]
 [0.70096913 0