In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

type(a)

numpy.ndarray

In [6]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# 2x2 identity matrix

identity = np.eye(2)
identity

array([[1., 0.],
       [0., 1.]])

In [ ]:
# range based creation

range_arr = np.arange(0, 10, 2)
print(range_arr, end="\n\n")

linspace = np.linspace(0, 1, 5)
print(linspace) # equally spaced nums

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]


In [25]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape, end="\n\n") # rows x cols
print(arr.ndim, end="\n\n")  # num of axes of an arr -> 2D matrix
print(arr.size, end="\n\n")  # total eles in an arr
print(arr.dtype, end="\n\n") # data type of eles in matrix

(2, 3)

2

6

int64



In [26]:
# arr.dtype = float
# arr.dtype

In [29]:
# indexing and listing

lst = np.array([1, 2, 3, 4, 5, 6])

print(lst[0], end="\n\n")
print(lst[-1], end="\n\n")
print(lst[:3], end="\n\n")

1

6

[1 2 3]



In [32]:
# 2D indexing

matrix = np.array([
    [1,2,3],
    [10,20,30],
    [11,12,13]
])

print(matrix[1, 2], end="\n\n") # row 1 col 2
print(matrix[:, 1], end="\n\n") # all row vals from col 1

30

[ 2 20 12]



In [39]:
# vectorized operations

# no loops required --> any linear operation run without loops on numpy arrs

vec = np.array([1,2,3,4,5])

print(vec + 100, end="\n\n")
print(vec * 100, end="\n\n")
print(vec ** 2, end="\n\n")

[101 102 103 104 105]

[100 200 300 400 500]

[ 1  4  9 16 25]



In [42]:
print(np.sqrt(vec), end="\n\n")
print(np.mean(vec), end="\n\n")
print(np.median(vec), end="\n\n")
print(np.std(vec), end="\n\n")
print(np.min(vec), np.max(vec), end="\n\n")

[1.         1.41421356 1.73205081 2.         2.23606798]

3.0

3.0

1.4142135623730951

1 5



In [46]:
# boolean masking

test = np.array([1, 2, 3, 4, 5])

mask = test > 2.5

print(test[mask])

print(test[test % 2 == 0])

[3 4 5]
[2 4]


In [52]:
# reshaping and flattening arrs

arr2 = np.arange(9)
print(arr2)
print(arr2.shape, end="\n\n")

res = arr2.reshape(3, 3)
print(res, end="\n\n")

flat = res.flatten()
print(flat)

[0 1 2 3 4 5 6 7 8]
(9,)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2 3 4 5 6 7 8]
