In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

type(a)

numpy.ndarray

In [6]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# 2x2 identity matrix

identity = np.eye(2)
identity

array([[1., 0.],
       [0., 1.]])