In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

type(a)

numpy.ndarray

In [6]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# 2x2 identity matrix

identity = np.eye(2)
identity

array([[1., 0.],
       [0., 1.]])

In [ ]:
# range based creation

range_arr = np.arange(0, 10, 2)
print(range_arr, end="\n\n")

linspace = np.linspace(0, 1, 5)
print(linspace) # equally spaced nums

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]


In [25]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape, end="\n\n") # rows x cols
print(arr.ndim, end="\n\n")  # num of axes of an arr -> 2D matrix
print(arr.size, end="\n\n")  # total eles in an arr
print(arr.dtype, end="\n\n") # data type of eles in matrix

(2, 3)

2

6

int64



In [26]:
# arr.dtype = float
# arr.dtype